profiles: prd
server:
  servlet:
    context-path: /lampblack
  port: 9090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      lampblackDB:
        name: lampblackDB
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.234:3306/lampblackdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: lampblack
        password: LB!QAZxsw2
        tns: lampblackDB
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        validation-query-timeout: 10000
        test-While-Idle: true
        test-on-borrow: false
        test-on-return: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        # 合并多个DruidDataSource的监控数据
        use-global-data-source-stat: true

      bosspubDB11:
        name: bosspubDB11
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.234:3306/lampblackdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: lampblack
        password: LB!QAZxsw2
        tns: lampblackDB
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        validation-query-timeout: 10000
        test-While-Idle: true
        test-on-borrow: false
        test-on-return: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        # 合并多个DruidDataSource的监控数据
        use-global-data-source-stat: true


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#  redis:
#    host: 172.32.148.34
#    port: 6379
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: -1
#    timeout: 3000
#  session:
#    store-type: redis

logging:
  path: log

uploadPath: /opt/upload

securityFilter:
  rediectErrorUrl:

# Socket配置
socket:
  # 监听端口 8068
  port: 8068
  # 线程池 - 保持线程数 20
  pool-keep: 20
  # 线程池 - 核心线程数 10
  pool-core: 10
  # 线程池 - 最大线程数 20
  pool-max: 20
  # 线程队列容量 10
  pool-queue-init: 10